# Generated by Django 5.2.7 on 2025-10-12 11:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AgenciaPaquete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_paquete", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("precio_total", models.FloatField()),
                ("duracion_dias", models.IntegerField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "codigo_departamento",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("nombre_departamento", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "codigo_municipio",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("nombre_municipio", models.CharField(max_length=255)),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="municipios",
                        to="api.departamento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TuristaRegistro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_encuesta", models.DateField()),
                (
                    "nombre_turista",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("genero", models.CharField(blank=True, max_length=50, null=True)),
                ("edad", models.IntegerField(blank=True, null=True)),
                ("rango_edad", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "nacionalidad",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "pais_residencia",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "motivo_viaje",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "otro_motivo_viaje",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "depto_origen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.departamento",
                    ),
                ),
                (
                    "municipio_encuestado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="encuestas_realizadas",
                        to="api.municipio",
                    ),
                ),
                (
                    "municipio_origen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="turistas_origen",
                        to="api.municipio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_rol", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GuiaPerfil",
            fields=[
                (
                    "guia",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("idiomas", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "especialidades",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("certificaciones", models.TextField(blank=True, null=True)),
                ("tarifa_por_hora", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AgenciaReservaPaquete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("numero_personas", models.IntegerField()),
                ("estado", models.CharField(max_length=50)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paquete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.agenciapaquete",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="usuario",
            name="departamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.departamento",
            ),
        ),
        migrations.CreateModel(
            name="AtractivoTuristico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_atractivo", models.CharField(max_length=255)),
                (
                    "tipo_categoria_principal",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("descripcion_breve", models.TextField(blank=True, null=True)),
                ("aprobado_publicar", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.municipio"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="usuario",
            name="municipio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.municipio",
            ),
        ),
        migrations.CreateModel(
            name="EmpresaPrestadorTuristico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("razon_social_o_nombre_comercial", models.CharField(max_length=255)),
                (
                    "nit",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("tipo_prestador", models.CharField(max_length=255)),
                (
                    "tipo_prestador_otro",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("es_formal", models.BooleanField(default=True)),
                ("rnt", models.CharField(blank=True, max_length=50, null=True)),
                ("descripcion_servicios", models.TextField(blank=True, null=True)),
                (
                    "direccion_principal",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "telefonos_contacto",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "email_contacto",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("pagina_web", models.URLField(blank=True, null=True)),
                ("aprobada_publicar", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_ultima_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.municipio"
                    ),
                ),
                (
                    "registrada_por_usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="empresas_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="agenciapaquete",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.empresaprestadorturistico",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="empresa_asociada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="empleados",
                to="api.empresaprestadorturistico",
            ),
        ),
        migrations.CreateModel(
            name="EncuestaPercepcion",
            fields=[
                (
                    "turista_registro",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="api.turistaregistro",
                    ),
                ),
                ("volveria", models.IntegerField(blank=True, null=True)),
                (
                    "experiencia_general_positiva",
                    models.IntegerField(blank=True, null=True),
                ),
                ("fecha_valoracion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="turistaregistro",
            name="registrado_por_usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="EventoTuristico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_evento", models.CharField(max_length=255)),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("publicado", models.BooleanField(default=False)),
                (
                    "municipio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.municipio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuiaDisponibilidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("disponible", models.BooleanField(default=True)),
                (
                    "guia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuiaReservaTour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora_inicio", models.DateTimeField()),
                ("duracion_horas", models.IntegerField()),
                ("estado", models.CharField(max_length=50)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tours_contratados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "guia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tours_guiados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IniciativaTuristica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_iniciativa", models.CharField(max_length=255)),
                (
                    "tipo_iniciativa",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("estado", models.CharField(blank=True, max_length=100, null=True)),
                ("presupuesto", models.FloatField(blank=True, null=True)),
                (
                    "municipio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.municipio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventarioTipoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_tipo", models.CharField(max_length=255)),
                ("categoria", models.CharField(blank=True, max_length=100, null=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("stock_minimo_deseado", models.IntegerField(blank=True, null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.empresaprestadorturistico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventarioItemIndividual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado", models.CharField(max_length=100)),
                ("fecha_compra", models.DateField(blank=True, null=True)),
                ("veces_usado", models.IntegerField(default=0)),
                ("fecha_ultimo_mantenimiento", models.DateField(blank=True, null=True)),
                ("notas_mantenimiento", models.TextField(blank=True, null=True)),
                (
                    "tipo_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.inventariotipoitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaqueteServicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_servicio", models.CharField(max_length=100)),
                ("id_servicio_especifico", models.IntegerField()),
                ("descripcion_servicio", models.TextField(blank=True, null=True)),
                (
                    "paquete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.agenciapaquete",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductoEventoEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("tipo", models.CharField(max_length=50)),
                ("precio", models.FloatField(blank=True, null=True)),
                ("fecha_evento", models.DateField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.empresaprestadorturistico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Promocion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_promocion",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("tipo_descuento", models.CharField(max_length=50)),
                ("valor_descuento", models.FloatField()),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.empresaprestadorturistico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecursoReservable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_recurso", models.CharField(max_length=255)),
                ("tipo_recurso", models.CharField(max_length=100)),
                ("capacidad", models.IntegerField()),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("precio_base", models.FloatField()),
                ("activo", models.BooleanField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.empresaprestadorturistico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nacionalidad", models.CharField(max_length=50)),
                ("cantidad", models.IntegerField(default=1)),
                ("fecha_registro", models.DateField()),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.empresaprestadorturistico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReglaPrecio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_regla", models.CharField(max_length=255)),
                ("tipo_regla", models.CharField(max_length=100)),
                ("valor_ajuste", models.FloatField()),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("dias_semana", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.empresaprestadorturistico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField()),
                ("estado", models.CharField(max_length=100)),
                ("monto_final", models.FloatField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "promocion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.promocion",
                    ),
                ),
                (
                    "recurso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.recursoreservable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.FloatField()),
                (
                    "metodo_pago",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "estado_pago",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fecha_pago", models.DateTimeField(auto_now_add=True)),
                (
                    "reserva",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.reserva"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RestauranteMenuProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_producto", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("precio", models.FloatField()),
                ("categoria", models.CharField(blank=True, max_length=100, null=True)),
                ("disponible", models.BooleanField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.empresaprestadorturistico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RestauranteMesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_mesa", models.CharField(max_length=100)),
                ("capacidad", models.IntegerField()),
                ("estado", models.CharField(max_length=50)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.empresaprestadorturistico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RestaurantePedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado", models.CharField(max_length=50)),
                ("total", models.FloatField(blank=True, null=True)),
                ("fecha_apertura", models.DateTimeField(auto_now_add=True)),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                (
                    "mesa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.restaurantemesa",
                    ),
                ),
                (
                    "mesero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RestaurantePedidoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField()),
                ("precio_unitario", models.FloatField()),
                ("estado", models.CharField(max_length=50)),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.restaurantepedido",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.restaurantemenuproducto",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="usuario",
            name="rol",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.rol",
            ),
        ),
        migrations.CreateModel(
            name="VacanteEmpleo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo_vacante", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                ("requisitos", models.TextField(blank=True, null=True)),
                (
                    "nombre_empleador_alternativo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tipo_contrato",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "salario_rango",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fecha_publicacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                ("activa", models.BooleanField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.empresaprestadorturistico",
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.municipio"
                    ),
                ),
                (
                    "publicada_por_usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiagnosticoTerritorial",
            fields=[
                (
                    "municipio",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="api.municipio",
                    ),
                ),
                ("anio_diagnostico", models.IntegerField()),
                (
                    "dimension_1_infraestructura",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "dimension_2_sostenibilidad",
                    models.FloatField(blank=True, null=True),
                ),
                ("resultado_total", models.FloatField(blank=True, null=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "registrado_por_usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
